name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}
softdepend: [EasyDB]

permissions:
  itemconomy.console:
    description: Allows use of the sign related commands.
commands:
  icsignbuy:
    description: Buy stuff
    usage: /icsignbuy <player> <price> <cmd>
  icsigndeposit:
    description: Deposit emeralds
    usage: /icsigndeposit <player> <amt>
  icsignwithdraw:
    description: Withdraw emeralds
    usage: /icsignwithdraw <player> <amt>
